name: Docker Image CI

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        name: swapnilsrivastava-boot
    - name: Download and Build the Docker image

      run: docker build . --file Dockerfile --tag swapnilsrivastava-boot:$(date +%s)
